;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ace-jump-char-mode
	ace-jump-move
	c-beginning-of-statement
	c-electric-colon
	c-electric-delete-forward
	c-electric-paren
	c-electric-semi&comma
	c-electric-slash
	c-electric-star
	c-end-of-statement
	dired-do-rename
	dired-flag-file-deletion
	eval-print-last-sexp
	forward-sentence
	helm-M-x
	iy-go-to-char--command
	kill-region
	mouse-yank-primary
	org-beginning-of-line
	org-delete-char
	org-end-of-line
	org-force-self-insert
	org-kill-line
	org-self-insert-command
	org-shiftleft
	org-shiftright
	org-yank
	suspend-frame
	undefined
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	c-forward-conditional
	c-indent-line-or-region
	comint-next-input
	comint-previous-input
	pop-global-mark
	save-some-buffers
	))
